name = "bitgnostiq"
license = "MIT"
licenselink = "https://github.com/bitgnostiq/kanso/blob/main/LICENSE"
description = ""

homepage = "https://github.com/bitgnostiq/kanso"

demosite = "TBA"

tags = ["blog", "minimal", "black", "personal", "simple",]
features = []

[author]
    name = "bitgnostiq"
    homepage = "https://bitgnostiq.dev"