baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Kansō'
themesDir = '../..'
theme = 'kanso'
Copyright = 'Sample custom notice © {year}'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    tabWidth = 4




[menu]
  [[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menu.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30


[params]
  [params.footer]
    showThemeAttribution = true
    showSocialLinks = true
    socialLinkType = "icon"

  [[params.footer.social]]
    text = "github"
    title = "github"
    link = "https://github.com/bitgnostiq/kanso"


  [[params.notFound.links]]
    title = "home"
    text = "Return Home"
    link = "/"
 [[params.notFound.links]]
    title = "posts"
    text = "Browse Posts"
    link = "/posts"
